[Params]
# A-амплитуда сигнала в относительных единицах
A=1
# f - частота несущей в Гц
f=1
# fd - частота дискретизации в Гц
fd=1
# От n1 десятичные числа
n1=0
# до n2  десятичные числа
n2=-1
# Разнос частот для FSK в Гц
df=50
# Скорость передачи в Бодах
rate=1
# 0 -> биты RANDOM; 1 -> meandr
meandr = 0
